### ISSUE TITLE
Docker Linux 环境下运行报错

### ISSUE THREAD

**Issue by x-haose** [pysunday/sdenv#4]
在Docker中的Linux环境下运行出现错误，但安装sdenv本身已经成功

dockerfile
```
FROM nikolaik/python-nodejs:python3.12-nodejs22

# 把系统源改为清华源
# 安装node-gyp所需要的依赖项
RUN sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's|http://security.debian.org/debian-security|https://mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gcc \
    g++ \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    libpng-dev \
    && npm install -g node-gyp

# 创建应用目录
WORKDIR /app

# 复制文件
COPY ./js ./js/
COPY ./src ./src
COPY ./requirements.lock ./

# 安装 Python 依赖
RUN sed -i '/^-e file:.*/d' requirements.lock && \
    PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock -i https://pypi.tuna.tsinghua.edu.cn/simple/

# 安装js依赖
RUN cd js && npm i && cd ..

# 设置容器入口点
ENTRYPOINT ["python", "-m", "src"]

```

下面是运行时的报错信息：
```
ERROR sdenv - Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/app/js/node_modules/sdenv-jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/app/js/node_modules/sdenv-jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/app/js/node_modules/sdenv-jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at evalmachine.<anonymous>:1:107447
    at evalmachine.<anonymous>:1:179703
    at evalmachine.<anonymous>:1:179743
    at Script.runInContext (node:vm:148:12)
    at main (/app/js/get_gett_token.js:15:24)
    at Object.<anonymous> (/app/js/get_gett_token.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1434:14) undefined
(node:118) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/modules/cjs/loader:1544
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /app/js/node_modules/sdenv/build/Release/documentAll.node: invalid ELF header
    at Module._extensions..node (node:internal/modules/cjs/loader:1544:18)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/app/js/node_modules/sdenv/browser/chrome/document.js:1:24)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by pysunday** [comment]
已经做好docker适配，今天有空更新

**Comment by pysunday** [comment]
代码已上传，具体看文档及对应提交的代码改动
